<a href="https://colab.research.google.com/github/BeforeTheTeaCools/MachineLearningPractice/blob/main/HiddenLayerPractice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#library
import tensorflow as tf
import pandas as pd

In [2]:
#data
file = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
data = pd.read_csv(file)
data.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
#one-hot encoding
data = pd.get_dummies(data)
data.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
print(data.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [5]:
#independent, dependent
ind = data[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep = data[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(ind.shape, dep.shape)

(150, 4) (150, 3)


In [6]:
#make model
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [7]:
#fit model
model.fit(ind, dep, epochs=100, verbose=0)
model.fit(ind, dep, epochs=10)
#loss decrease = it's learning

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1104 - accuracy: 0.9667
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1069 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1107 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 0.1095 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1099 - accuracy: 0.9600
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1064 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 0.1035 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 6ms/step - loss: 0.1067 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1001 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0999 - accuracy: 0.9800


In [8]:
#use the model
print(model.predict(ind[0:5]))
print(dep[0:5])

[[9.9984014e-01 3.3571479e-05 1.2616317e-04]
 [9.9962676e-01 1.1978098e-04 2.5347550e-04]
 [9.9963570e-01 9.3641291e-05 2.7066303e-04]
 [9.9920267e-01 3.3835709e-04 4.5893344e-04]
 [9.9982482e-01 3.6567726e-05 1.3859973e-04]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
