<a href="https://colab.research.google.com/github/BeforeTheTeaCools/MachineLearningPractice/blob/main/HiddenLayerPractice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#library
import tensorflow as tf
import pandas as pd

In [ ]:
#data
file = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
data = pd.read_csv(file)
data.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
#one-hot encoding
data = pd.get_dummies(data)
data.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
print(data.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
#independent, dependent
ind = data[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep = data[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(ind.shape, dep.shape)

(150, 4) (150, 3)


In [12]:
#make model
X = tf.keras.layers.Input(shape=[4])

H = tf.keras.layers.Dense(8)(X)#separated activision code and added batchnormalization for better accuracy
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [14]:
#fit model
model.fit(ind, dep, epochs=1000, batch_size=150)
#loss decrease = it's learning

Epoch 1/1000
1/1 [==============================] - 1s 1s/step - loss: 1.4309 - accuracy: 0.1267
Epoch 2/1000
1/1 [==============================] - 0s 7ms/step - loss: 1.3372 - accuracy: 0.1733
Epoch 3/1000
1/1 [==============================] - 0s 6ms/step - loss: 1.2807 - accuracy: 0.1933
Epoch 4/1000
1/1 [==============================] - 0s 11ms/step - loss: 1.2370 - accuracy: 0.2133
Epoch 5/1000
1/1 [==============================] - 0s 6ms/step - loss: 1.2000 - accuracy: 0.2467
Epoch 6/1000
1/1 [==============================] - 0s 6ms/step - loss: 1.1671 - accuracy: 0.2667
Epoch 7/1000
1/1 [==============================] - 0s 10ms/step - loss: 1.1371 - accuracy: 0.3267
Epoch 8/1000
1/1 [==============================] - 0s 6ms/step - loss: 1.1091 - accuracy: 0.3933
Epoch 9/1000
1/1 [==============================] - 0s 7ms/step - loss: 1.0830 - accuracy: 0.4000
Epoch 10/1000
1/1 [==============================] - 0s 6ms/step - loss: 1.0584 - accuracy: 0.4200
Epoch 11/1000
1/1 

In [15]:
#use the model
print(model.predict(ind[0:5]))
print(dep[0:5])

[[9.9973482e-01 2.6168220e-04 3.4616444e-06]
 [9.9691510e-01 3.0496509e-03 3.5245772e-05]
 [9.9962485e-01 3.6968928e-04 5.4593511e-06]
 [9.9873096e-01 1.2597172e-03 9.2747723e-06]
 [9.9995601e-01 4.2192783e-05 1.8371300e-06]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
