<a href="https://colab.research.google.com/github/BeforeTheTeaCools/MachineLearningPractice/blob/main/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#library
import tensorflow as tf
import pandas as pd

In [2]:
#data
file = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
data = pd.read_csv(file)
data.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [5]:
#one-hot encoding
data = pd.get_dummies(data)
data.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [6]:
print(data.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [9]:
#independent, dependent
ind = data[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep = data[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(ind.shape, dep.shape)

(150, 4) (150, 3)


In [51]:
#make model
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [54]:
#fit model
model.fit(ind, dep, epochs=100, verbose=0)
model.fit(ind, dep, epochs=10)
#loss decrease = it's learning

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4018 - accuracy: 0.9200
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4027 - accuracy: 0.9067
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.4005 - accuracy: 0.9000
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.3996 - accuracy: 0.9133
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3998 - accuracy: 0.9333
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3981 - accuracy: 0.9133
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 0.3981 - accuracy: 0.9067
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3981 - accuracy: 0.9200
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3957 - accuracy: 0.9200
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3959 - accuracy: 0.9333


In [56]:
#use the model
model.predict(ind[0:5])

array([[0.9575561 , 0.03763913, 0.00480475],
       [0.9163239 , 0.07345686, 0.01021934],
       [0.9415666 , 0.05077712, 0.00765627],
       [0.91713095, 0.06983895, 0.01303014],
       [0.9628184 , 0.032669  , 0.00451265]], dtype=float32)

In [57]:
model.predict(ind[-5:])

array([[0.00287   , 0.4376273 , 0.5595027 ],
       [0.00350992, 0.44462886, 0.5518613 ],
       [0.00465627, 0.4213343 , 0.5740095 ],
       [0.00301748, 0.31240082, 0.68458176],
       [0.0062191 , 0.3533641 , 0.6404168 ]], dtype=float32)

In [58]:
print(dep[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [59]:
print(dep[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [60]:
model.get_weights()

[array([[ 0.079895  ,  0.11249759, -0.57395136],
        [ 0.49398383, -0.9443938 , -0.8418612 ],
        [-1.5140615 , -0.49174607,  0.2812665 ],
        [-1.9477353 , -0.23000093,  0.01583608]], dtype=float32),
 array([ 0.12341152, -0.01966834, -0.06746757], dtype=float32)]